// Mocks generated by Mockito 5.4.4 from annotations
// in mhd_ghaith_top_stories/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mhd_ghaith_top_stories/app/storage/app_storage.dart' as _i12;
import 'package:mhd_ghaith_top_stories/core/features/data/remote_data_source/http_client.dart'
    as _i13;
import 'package:mhd_ghaith_top_stories/core/features/data/remote_data_source/models/params/params_model.dart'
    as _i14;
import 'package:mhd_ghaith_top_stories/core/features/domain/entities/error_entity/error_entity.dart'
    as _i6;
import 'package:mhd_ghaith_top_stories/core/network/network_info.dart' as _i10;
import 'package:mhd_ghaith_top_stories/features/top_stories/data/remote/data_sources/top_stories_remote_data_source.dart'
    as _i9;
import 'package:mhd_ghaith_top_stories/features/top_stories/data/remote/models/params/top_stories_params.dart'
    as _i8;
import 'package:mhd_ghaith_top_stories/features/top_stories/data/remote/models/response/top_stories_api_response.dart'
    as _i3;
import 'package:mhd_ghaith_top_stories/features/top_stories/domain/entities/top_stories_entity.dart'
    as _i7;
import 'package:mhd_ghaith_top_stories/features/top_stories/domain/repositories/itop_stories_repository.dart'
    as _i4;
import 'package:mhd_ghaith_top_stories/features/top_stories/domain/use_cases/get_top_stories_use_case.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTopStoriesResponse_1 extends _i1.SmartFake
    implements _i3.TopStoriesResponse {
  _FakeTopStoriesResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeITopStoriesRepository_2 extends _i1.SmartFake
    implements _i4.ITopStoriesRepository {
  _FakeITopStoriesRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITopStoriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITopStoriesRepository extends _i1.Mock
    implements _i4.ITopStoriesRepository {
  MockITopStoriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>> getTopStories(
          _i8.TopStoriesParams? topStoriesParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopStories,
          [topStoriesParams],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>>.value(
                _FakeEither_0<_i6.ErrorEntity, _i7.TopStoriesEntity>(
          this,
          Invocation.method(
            #getTopStories,
            [topStoriesParams],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>>);
}

/// A class which mocks [ITopStoriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITopStoriesRemoteDataSource extends _i1.Mock
    implements _i9.ITopStoriesRemoteDataSource {
  MockITopStoriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.TopStoriesResponse> getTopStories(
          _i8.TopStoriesParams? topStoriesParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopStories,
          [topStoriesParams],
        ),
        returnValue:
            _i5.Future<_i3.TopStoriesResponse>.value(_FakeTopStoriesResponse_1(
          this,
          Invocation.method(
            #getTopStories,
            [topStoriesParams],
          ),
        )),
      ) as _i5.Future<_i3.TopStoriesResponse>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i10.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [GetTopStoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopStoriesUseCase extends _i1.Mock
    implements _i11.GetTopStoriesUseCase {
  MockGetTopStoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ITopStoriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeITopStoriesRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ITopStoriesRepository);

  @override
  set repository(_i4.ITopStoriesRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>> call(
          _i8.TopStoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>>.value(
                _FakeEither_0<_i6.ErrorEntity, _i7.TopStoriesEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, _i7.TopStoriesEntity>>);
}

/// A class which mocks [AppStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppStorage extends _i1.Mock implements _i12.AppStorage {
  MockAppStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setAPIKey({required String? apiKeyValue}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAPIKey,
          [],
          {#apiKeyValue: apiKeyValue},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> removeAPIKey() => (super.noSuchMethod(
        Invocation.method(
          #removeAPIKey,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool getFirstAppOpen() => (super.noSuchMethod(
        Invocation.method(
          #getFirstAppOpen,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setCachedStories({required String? stories}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCachedStories,
          [],
          {#stories: stories},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> removeCachedStories() => (super.noSuchMethod(
        Invocation.method(
          #removeCachedStories,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [TopStoriesHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i13.TopStoriesHttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<Map<String, dynamic>> get(
          _i14.ParamsModel<_i14.BaseBodyModel>? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [model],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> post(
          _i14.ParamsModel<_i14.BaseBodyModel>? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [model],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}
