on:
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '19.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          name: top-stories-v1.0.0(1).apk
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.0(1)
          token: ${{ secrets.TOKEN }}